name: Process Links and Deploy Site

on:
  push:
    branches: [ main ]
    paths: 
      - 'links.md'
      - 'config/**'
      - 'scripts/**'
      - '.github/workflows/**'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  process-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Full history for git log timestamps
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install
    
    - name: Install Playwright for PDF generation
      run: |
        bun install
        bunx playwright install chromium
    
    - name: Scrape content from URLs
      run: |
        # Only refresh scraped content older than 30 days
        REFRESH_DATE=$(date -d '30 days ago' --iso-8601)
        bun run scripts/scrapeContent.ts --refresh-older-than $REFRESH_DATE

    - name: Generate static site
      run: bun run scripts/generateSite.ts
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 